-- ── Catalog Table: Profile Patterns ────────────────────────────

create table public.profile_patterns (
  id           uuid              primary key default gen_random_uuid(),
  slug         text              not null unique,
  name         text              not null,
  rarity       public.cosmetic_rarity not null default 'common',
  price_dp     integer           not null default 0,
  style_config jsonb             not null default '{}'
);

-- ── Profiles Extension ────────────────────────────────────────

alter table public.profiles
  add column if not exists equipped_pattern_id uuid references public.profile_patterns(id) on delete set null;

-- ── Inventory Expansion ───────────────────────────────────────

-- Drop the autogenerated check constraint and add a new one including 'profile_pattern'
alter table public.user_inventory drop constraint if exists user_inventory_asset_type_check;
alter table public.user_inventory add constraint user_inventory_asset_type_check
  check (asset_type in ('avatar_frame', 'profile_background', 'stat_style', 'profile_pattern'));

-- ── RLS & Permissions ─────────────────────────────────────────

alter table public.profile_patterns enable row level security;

create policy "public read profile_patterns"
  on public.profile_patterns for select using (true);

grant select on public.profile_patterns to authenticated, anon;

-- ── Seed Data: Profile Patterns ───────────────────────────────

insert into public.profile_patterns (slug, name, rarity, price_dp, style_config) values
  ('neural_threads', 'Нейронные нити', 'rare',      750,  '{"pattern_type":"neural"}'),
  ('low_poly',       'Полигоны',       'epic',      1200, '{"pattern_type":"low_poly"}'),
  ('isometric',      'Изометрия',      'legendary', 2500, '{"pattern_type":"isometric"}'),
  ('dot_matrix',     'Точки',          'common',    300,  '{"pattern_type":"dot_matrix"}')
on conflict (slug) do nothing;

-- ── Update Leaderboard RPC ────────────────────────────────────

drop function if exists public.get_daily_leaderboard();

create or replace function public.get_daily_leaderboard()
returns table (
  user_id                uuid,
  username               text,
  avatar_url             text,
  equipped_frame_id      uuid,
  equipped_background_id uuid,
  equipped_pattern_id    uuid,
  equipped_stat_style_id uuid,
  total_xp               integer,
  daily_xp               integer,
  rank                   bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with scores as (
    select
      p.id                       as user_id,
      p.username,
      p.avatar_url,
      p.equipped_frame_id,
      p.equipped_background_id,
      p.equipped_pattern_id,
      p.equipped_stat_style_id,
      p.total_xp,
      (
        coalesce(
          (select sum(hl.xp_awarded)
           from   public.habit_logs hl
           where  hl.user_id      = p.id
             and  hl.completed_at = current_date),
          0
        ) +
        coalesce(
          (select sum(fs.xp_gained)
           from   public.focus_sessions fs
           where  fs.user_id      = p.id
             and  fs.is_completed = true
             and  (fs.created_at at time zone 'UTC')::date = current_date),
          0
        ) +
        coalesce(
          (select sum(a.xp_reward)
           from   public.user_achievements ua
           join   public.achievements      a on a.id = ua.achievement_id
           where  ua.user_id  = p.id
             and  (ua.earned_at at time zone 'UTC')::date = current_date),
          0
        )
      )::integer as daily_xp
    from public.profiles p
  )
  select
    user_id,
    username,
    avatar_url,
    equipped_frame_id,
    equipped_background_id,
    equipped_pattern_id,
    equipped_stat_style_id,
    total_xp,
    daily_xp,
    rank() over (order by daily_xp desc, total_xp desc) as rank
  from  scores
  order by daily_xp desc, total_xp desc
  limit 50;
$$;

